"""Render the machine-readable Opportunity study report as a Markdown research summary.

The Markdown is generated: every number comes from the JSON report. Interpretation
lives in a separate, hand-written document so that facts and judgement stay apart.
"""

from __future__ import annotations

STATES = ("HIGH", "NORMAL", "LOW")


def _pct(v, digits=1):
    return "—" if v is None else f"{v * 100:.{digits}f}%"


def _num(v, digits=3):
    return "—" if v is None else f"{v:.{digits}f}"


def render(report: dict, run: dict, outcomes_meta: dict) -> str:
    cfg = report["config"]
    primary = report["bootstrap_high_minus_low_primary_cell"]["cell"]
    slices = report["slices"]
    lines = [
        "# Opportunity V1 — Historical Evaluation (generated)",
        "",
        "> Generated by `bitmomo-lab opportunity-study`. Research only; not a public accuracy claim.",
        "> Interpretation: see `M1_OPPORTUNITY_V1_FINDINGS.md`.",
        "",
        "## Identity",
        "",
        f"* Evaluation: `{report['evaluation_id']}` (config `config/opportunity_v1_evaluation.json`, hypotheses `registry/hypotheses.json`)",
        f"* Engine: `{run['engine']['engine_id']}` {run['engine']['engine_version']} / methodology `{run['engine']['methodology_version']}` / parameters sha256 `{run['engine']['parameters_sha256'][:16]}…`",
        f"* Mode: `{run['mode']}`. Run `{run['run_id']}`, logical output sha256 `{run['output']['logical_content_sha256']}`",
        f"* Input: `{run['inputs'][0]['dataset']}` content sha256 `{run['inputs'][0]['content_sha256']}`",
        f"* Outcomes: content sha256 `{outcomes_meta['content_sha256']}`; entry = close at cutoff, delay {cfg['entry']['delay_seconds']} s",
        f"* Replay path: `{run['verification']['path']}`, cross-checked against the per-cutoff PIT path on {run['verification']['sample_size']} random cutoffs (0 mismatches)",
        f"* Code: `{run['code']['code_commit'][:12]}` (dirty: {run['code']['code_dirty']})",
        "",
        "## Dataset, coverage and missingness",
        "",
        f"* Cutoffs (15m): {report['coverage']['cutoffs']:,} from {run['window']['first_cutoff']} to {run['window']['last_cutoff']}",
        f"* Evaluable (engine available and every horizon settled): {report['coverage']['evaluable']:,}",
        "* Engine status counts: " + ", ".join(f"`{k}` {v:,}" for k, v in report["coverage"]["engine_status"].items()),
        "* Outcome paths incomplete by horizon: " + ", ".join(f"{k} {v}" for k, v in report["coverage"]["outcome_incomplete_by_horizon"].items()),
        f"* Volatility context unavailable among evaluable rows: {report['coverage']['vol_context_unavailable_among_evaluable']:,} (warm-up: 20 + 180 days)",
        f"* abs_return_60m missing among evaluable rows: {report['coverage']['abs_return_60m_missing_among_evaluable']:,}",
        "",
        "Rows overlap heavily (15-minute cutoffs, horizons up to 6h). Row counts are not independent samples; distinct UTC days are shown alongside.",
        "",
        "## Pre-registered hypotheses",
        "",
        "| Id | Result | Evidence |",
        "|---|---|---|",
    ]
    for h in report["hypotheses"]:
        lines.append(f"| {h['id']} | **{h['result']}** | `{_compact(h['evidence'])}` |")
    lines += [
        "",
        f"Hypotheses tested: {len(report['hypotheses'])}. Descriptive cells: {report['cells_evaluated_per_slice']} "
        f"(6 horizons × 3 thresholds) × {report['slices_evaluated']} slices, plus {len(report['walk_forward'])} walk-forward folds.",
        "",
        "## Performance by horizon (full sample and holdout)",
        "",
    ]
    for name in ("full", "segment:holdout"):
        s = slices[name]
        lines += [f"### {name} — evaluable {s['evaluable']:,} rows, {s['distinct_days']:,} days; state share "
                  + ", ".join(f"{k} {_pct(v)}" for k, v in s["state_share"].items()), "",
                  "| Cell | Base rate | HIGH | NORMAL | LOW | Ordered | HIGH−LOW (pp) | AUC percentile | AUC raw range | AUC abs 60m ret |",
                  "|---|---:|---:|---:|---:|:---:|---:|---:|---:|---:|"]
        for key, c in s["cells"].items():
            b = c["by_state"]
            lines.append(f"| {key} | {_pct(c['base_rate'])} | {_pct(b['HIGH']['rate'])} | {_pct(b['NORMAL']['rate'])} | "
                         f"{_pct(b['LOW']['rate'])} | {'✔' if c['ordered_high_normal_low'] else '✘'} | "
                         f"{_num(c['high_minus_low_pp'], 1)} | {_num(c['auc']['activity_percentile'])} | "
                         f"{_num(c['auc']['range_60m_pct'])} | {_num(c['auc']['abs_return_60m'])} |")
        lines.append("")
    lines += ["## Stability across periods (primary cell " + primary + ")", "",
              "| Slice | Evaluable | Days | HIGH | NORMAL | LOW | Ordered | AUC percentile | Share HIGH | Share LOW |",
              "|---|---:|---:|---:|---:|---:|:---:|---:|---:|---:|"]
    for name, s in slices.items():
        if "cells" not in s:
            lines.append(f"| {name} | 0 | 0 | — | — | — | — | — | — | — |")
            continue
        c = s["cells"][primary]
        b = c["by_state"]
        lines.append(f"| {name} | {s['evaluable']:,} | {s['distinct_days']:,} | {_pct(b['HIGH']['rate'])} | "
                     f"{_pct(b['NORMAL']['rate'])} | {_pct(b['LOW']['rate'])} | {'✔' if c['ordered_high_normal_low'] else '✘'} | "
                     f"{_num(c['auc']['activity_percentile'])} | {_pct(s['state_share']['HIGH'])} | {_pct(s['state_share']['LOW'])} |")
    lines += ["", "### Day-clustered bootstrap: HIGH − LOW event rate, primary cell", "",
              "| Slice | Estimate (pp) | 95% CI (pp) | Days |", "|---|---:|---|---:|"]
    for name, b in report["bootstrap_high_minus_low_primary_cell"].items():
        if name == "cell" or b.get("estimate") is None:
            continue
        lines.append(f"| {name} | {b['estimate'] * 100:.1f} | [{b['ci95'][0] * 100:.1f}, {b['ci95'][1] * 100:.1f}] | {b['days']:,} |")
    lines += ["", "## Walk-forward (expanding, by calendar year)", "",
              "Opportunity V1 has no fitted parameters. The fixed-quartile baseline is refit each fold on all prior years (purged).",
              "",
              "| Test year | Train rows | Opportunity ordered | Opp. HIGH−LOW (pp) | Opp. share HIGH / LOW | Fixed baseline ordered | Fixed share HIGH / LOW |",
              "|---|---:|:---:|---:|---|:---:|---|"]
    for fold in report["walk_forward"]:
        t = fold["test"]
        c = t["cells"][primary]
        fb = c["fixed_quartile_baseline"]
        lines.append(f"| {fold['test_year']} | {fold['train_rows']:,} | {'✔' if c['ordered_high_normal_low'] else '✘'} | "
                     f"{_num(c['high_minus_low_pp'], 1)} | {_pct(t['state_share']['HIGH'])} / {_pct(t['state_share']['LOW'])} | "
                     f"{'✔' if fb['ordered_high_normal_low'] else '✘'} | "
                     f"{_pct(t['fixed_quartile_state_share']['HIGH'])} / {_pct(t['fixed_quartile_state_share']['LOW'])} |")
    comparison = report["p02c_comparison"]
    lines += ["", "## Reproduction of published P0.2C tables (≥0.30% excursion)", "",
              f"{comparison['within_1pp']} of {comparison['total']} cells within ±1.0 pp; max |diff| {comparison['max_abs_diff_pp']:.2f} pp.",
              "", "| Table | Year | State | Horizon | Published | Platform | Diff (pp) |", "|---|---|---|---:|---:|---:|---:|"]
    for r in comparison["rows"]:
        lines.append(f"| {r['table']} | {r.get('year', '')} | {r['state']} | {r.get('horizon_minutes', 60)}m | "
                     f"{r['published_pct']:.1f}% | {r['platform_pct']:.2f}% | {r['diff_pp']:+.2f} |")
    lines += ["", "## PIT assumptions", "",
              "* Engine input: USD-M 5m candles with `available_at = close boundary`, read through `PITFrame.as_of(cutoff)`.",
              "* Outcomes: settled separately; `available_at = cutoff + 6h`; joined to records only in evaluation.",
              "* Baseline thresholds: fitted on development data only (`DevelopmentSlice`, purge 6h), or on prior years in walk-forward.",
              "* Volatility context: a day's value becomes available after that UTC day closes.", ""]
    return "\n".join(lines)


def _compact(value) -> str:
    import json

    def shorten(v):
        if isinstance(v, float):
            return round(v, 4)
        if isinstance(v, dict):
            return {k: shorten(x) for k, x in v.items()}
        return v

    return json.dumps(shorten(value), separators=(",", ":"))
